cart/urls.py
from django.urls import path
from . import views


app_name="cart"
urlpatterns=[
    path("",views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path("remove/<int:product_id>/",views.cart_remove,name="cart_remove"),
    path("full_remove/<int:product_id>/", views.full_remove, name="full_remove"),

]

ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include("shopcart.urls")),
    path("search/",include("search_app.urls")),
    path("cart/",include("cart.urls")),
]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views


app_name="search_app"
urlpatterns=[
    path("",views.searchResult,name="searchResult"),
]

shopcart/urls.py
from django.urls import path
from . import views
app_name="shopcart"
urlpatterns = [
    path("",views.allProCart,name="allProCat"),
    path("<slug:c_slug>/",views.allProCart,name="product_by_category"),
    path("<slug:c_slug>/<slug:product_slug>/", views.proDetail, name="proCatetil")

]

cart/models.py
from django.db import models
from shopcart.models import Product
# Create your models here.


class Cart(models.Model):

    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)


    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'


    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return '{}'.format(self.product)

search_app/models.py
from django.db import models

# Create your models here.

shopcart/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField()
    image=models.ImageField(upload_to="category",blank=True)


    class Meta:
        ordering=("name",)
        verbose_name="category"
        verbose_name_plural="categories"

    def __str__(self):
        return '{}'.format(self.name)



    def get_url(self):
        return reverse("shopcart:product_by_category",args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    price=models.DecimalField(max_digits=100,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="product",blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(blank=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('shopcart:proCatetil',args=[self.category.slug,self.slug])

    class Meta:
        ordering=("name",)
        verbose_name="product"
        verbose_name_plural="products"

    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist

from shopcart.models import Product

from .models import Cart,CartItem


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')



def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render

from shopcart.models import Product
from django.db.models import Q



def searchResult(request):
    query=None
    products=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        context={'query':query,'products':products}
        return render(request,'search.html',context)

shopcart/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage



def allProCart(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page',1))
    except:
        page=1

    try:
        products=paginator.page(page)
    except  (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return  render(request,'category.html',{'category':c_page,'products':products })








def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

    #return render(request,'product.html')

shopcart/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{%endblock%}">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>

<div>
    {% include 'footer.html' %}
<!--    <script src="{% static 'js/popper.min.js' %}"></script>-->
<!--    <script src="{% static 'js/bootstrap.min.js' %}"></script>-->

</div>


</body>
</html>

shopcart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

this is your cart page. Proceed to review your items and place the order
{% endblock %}

{% block title %}
cart-ABC Company Pvt Ltd
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my title">
            your shop cart is empty
        </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'shopcart:allProCat' %}">please click here</a>to continue shopping.
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            your shopping cart
        </h1>

    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your items
                </th>
            </tr>

            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{cart_item.product.get_url}}">
                        <img class="float-left rounded custom_image" src="{{cart_item.product.image.url}}" style="width:100px;height:100px" alt=""></a>

                </td>
                <td class="text-left">
                    {{ cart_item.product.name }}
                    <br>
                    SKU:{{ cart_item.product.id }}
                    <br>
                    price:${{ cart_item.product.price }}
                    <br>
                    Qty:{{ cart_item.quantity }} X ${{ cart_item }}
                </td>
                <td>
                    ${{ cart_item.sub_total }}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">  <i class="fa fa-plus"></i> </a> <br>
                        &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus"></i> </a>
                    <br>
                    &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-trash"></i> </a>

                </td>
                {%else%}
                <td>

                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-minus"></i></a> <br>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash"></i></a>

                </td>
            </tr>
            {% endif %}
            {% endfor %}

            </tbody>

        </table>

    </div>
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Check out
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before proceeding the order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    your Total is:<strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{%url 'shopcart:allProCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue
                shopping</a>
        </div>
        {% endif %}

    </div>

</div>


{% endblock %}

shopcart/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description | truncatewords:155 }}
    {% else %}
        Welcome to ABC Shop here you explore your favorites!!!!!!!!!
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.description }}ABC
    {% else %}
        see your new collections
    {% endif %}
{% endblock %}


{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p><a href="{%url 'shopcart:allProCat' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="mx_auto">
            {% if category %}
            <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}" style="width:100%;height:200px;">
        </div> <br>
        <div>
            <h1 class="text-center my-title">{{ category.name }}</h1>
            <p class="text-justify">{{ category.description }}</p>


        </div>
        {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/logo.png' %}" style="width:100%;height:500px;"
                 alt="our products">


        </div>
        <br>
<div>
    <h1 class="text-center my-title">Our products</h1>
    <p class="text-justify"> Cras sodales enim et nulla sollicitudin, eget suscipit dui congue. Phasellus a suscipit
        vulputate ut sem sed, sollicitudin tempus libero. Donec fringilla magna nec libero gravida, ut rutrum lorem
        facilisis. Sed consectetur erat in dolor mattis ornare. Fusce et odio quis urna venenatis tristique eget a ex.
        Cras luctus imperdiet purus nec elementum. Phasellus velit tortor, hendrerit dapibus risus eu, posuere iaculis
        odio. Fusce eu lobortis sapien, quis ullamcorper purus. Praesent egestas consectetur purus, vel molestie tortor
        rutrum vitae. Suspendisse potenti. Sed ipsum tortor, suscipit at nunc id, fringilla consectetur leo. Nam massa
        odio, malesuada in justo eget, congue congue purus. Quisque bibendum nunc risus. </p>
</div>
{% endif %}





<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4">
            <div class="row">

            <div class="card text-center" style="width:400px;height:500px;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:50%;height:40%" src="{{product.image.url}}"
                                                   alt={{product.name}}""></a>
                <div class="card-body">
                    <div>Name:{{ product.name }}</div>
                    <div>Rs:{{ product.price }}</div>

                </div>
                </div>
            </div>
        </div>
                    {%endfor%}

        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}"
                   class="btn btn-light btn-sm{%if products.number == pg%} active {%endif%}">{{pg}}</a>

                {% endfor %}
            </div>
            {% endif %}

        </div>
        <br>

    </div>
</div>
{% endblock %}

shopcart/templates/footer.html
<footer class="footer navbar-fixed-bottom my_footer">
    <p class="text-center ">
        &copy;ABC Pvt.Ltd .All Rights Reserved
    </p>
</footer>

shopcart/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopcart:allProCat' %}"><img src="{% static 'img/abc.png' %}" alt="logoimage"></a>
    </center>
</header>

shopcart/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shopcart:allProCat' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                <li class="nav-item dropdown {% if 'shopcart' in request.path %} active {% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        SHOP
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shopcart:allProCat' %}">All Products</a></li>

                        {% for cart in links %}
                        <li><a class="dropdown-item" href="{{ cart.get_url }}">{{ cart.name }}</a></li>

                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-arrow-down"></i>
                        ({{item_count}})</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit"><i class="fa fa-magnifying-glass"></i>Search
                </button>
            </form>
        </div>
    </div>
</nav>

shopcart/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{{ product.description | truncatewords:155 }}

{% endblock %}

{% block title %}
{% if product %}
{{ product.name }}ABC

{% endif %}
{% endblock %}


{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p>
            <a href="{%url 'shopcart:allProCat'%}">Home</a>|
            <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}
        </p>
    </div>
    <div class="container">
        <div class="row">
            <div class="card mb-3" style="max-width: 800px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ product.image.url }}" alt="{{ product.name }}" >

                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h1 class="my_product_title">{{product.name}}</h1>
                            <p class="my_title">product description:</p>

                            <p class="text-justify my_prod_text">${{product.description}}</p>
                            <p>${{product.price}}</p>
                            {% if products.stock <= 0 %}
                            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                            {% else %}
                            <a class="btn btn-warning" href="{% url 'cart:add_cart' product.id%}">Add to cart</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{%endblock%}

shopcart/templates/search.html
{% extends 'base.html'%}
{% load static %}
{% block metadescription %}

we have variety of products.
{% endblock %}

{% block title %}
search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">

        you have searched for :<b>{{query}}</b>
    </p>
</div>
<div class="row mx_auto">
    {% for product in products %}

    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 2 xl-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}"
                                               alt={{product.name}}""></a>
            <div class="card-body">
                <div>{{product.name}}</div>
                <div>{{product.price}}</div>


            </div>
        </div>

    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">
            0 results found
        </p>
    </div>
    {%endfor%}
</div>
</div>
{%endblock%}